name: Deploy
on:
  push:
    branches:
    - staging
    - prod

jobs:
  build:
    name:
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: docker://yuvipanda/hubploy:20191210215236cfab2d
        name: build & push image if needed
        with:
          args: build myhub --check-registry --push
      - uses: docker://yuvipanda/hubploy:20191210215236cfab2d
        name: Setup Helm
        with:
          entrypoint: /bin/bash
          args: -c "helm init --client-only && helm repo add jupyterhub https://jupyterhub.github.io/helm-chart/ && helm repo update"
      - uses: docker://yuvipanda/hubploy:dev
        name: Deploy to staging
        if: github.ref == 'refs/heads/staging'
        with:
          args: deploy myhub hub staging
      - uses: docker://yuvipanda/hubploy:20191210215236cfab2d
        name: Deploy to prod
        if: github.ref == 'refs/heads/prod'
        with:
          args: deploy myhub hub prod
